using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;

public class PlayerMovement : MonoBehaviour
{
    private const int speed = 4;
    private const float dashSpeed = 8; // La velocidad de dash es el doble de la velocidad normal
    private float dashDuration = 0.3f; // La duraci√≥n del dash en segundos

    private Vector2 movement;
    private Rigidbody2D rb;
    private Animator animator;

    private bool isDashing = false;

    private float speedMultiplier = 1f;

    private bool isDead;

    private void Awake()
    {
        rb = GetComponent<Rigidbody2D>();
        animator = GetComponent<Animator>();

    #if UNITY_ANDROID || UNITY_IOS
        speedMultiplier = 1.5f;
    #endif


    }

    public bool IsDead{
        get{
            return isDead;
        }

        set{
            isDead = value;
        }
    }

    private void OnMovement(InputValue value)
    {
        if(isDead==false){
        movement = value.Get<Vector2>();
        animator.SetFloat("X", movement.x);
        animator.SetFloat("Y", movement.y);
        }

    }

    private void OnDash(InputValue value)
    {
        if (!isDashing && value.isPressed)
        {
            Vector2 dashDirection = movement.normalized;
            rb.velocity = dashDirection * dashSpeed;
            isDashing = true;
            StartCoroutine(StopDashingAfterDelay());
        }
    }

    private IEnumerator StopDashingAfterDelay()
    {
        yield return new WaitForSeconds(dashDuration);
        rb.velocity = Vector2.zero;
        isDashing = false;
    }

    private void FixedUpdate()
    {
        if (!isDashing)
        {
            rb.velocity = movement * speed * speedMultiplier * Time.deltaTime;
        }
    }
}
