using UnityEngine;

public class EnergyBullet2 : MonoBehaviour
{
   [SerializeField] private float velocidad;
   [SerializeField] private float da침o;

   private void Update()
   {
      transform.Translate(Vector2.left * velocidad * Time.deltaTime);
   }

   private void OnTriggerEnter2D(Collider2D other)
   {
         if(other.CompareTag("Jugador1"))
         {
            other.GetComponent<Player>().TomarDa침o(da침o);
            Destroy(gameObject);
         }
         else if(other.CompareTag("Bala1"))
         {
            Debug.Log("La bala 2 colision칩 con otra bala");
            Destroy(gameObject);
            Destroy(other.gameObject); // Destroy the other bullet here
         }
   }
}
